### ISSUE TITLE
Please provide usage examples

### ISSUE THREAD

**Issue by bionicles** [alexandre-ricciardi/one-graph#1]
This looks like an amazing project because Rust is awesome and so is openCypher. 

Would you be openminded to add a little blurb to the README about how to import this like a library and run queries on it? 

I'm tinkering with a medical records project (just sandbox data for now, nothing critical) and wanted an embedded database to go with it. 

Sqlite is reliable but I really love openCypher, and i'm using rust. Can this be embedded in another rust crate like a graph DB library?

Edit: although, alas, I don't think I can use it since it's GPL3 and I wanted to license my project MIT/Apache for health companies to use. How committed are you to GPL3 vs other licenses which might allow folks to more easily commercialize products which use OneGraph?

**Comment by alexandre-ricciardi** [comment]
Hi,

**Comment by alexandre-ricciardi** [comment]
Hi,

Yes it also aims to be an embeddable graph db, but at the moment it is not quite complete, and there's still a lot to do.
OK I'll think about the licensing issue.

**Comment by alexandre-ricciardi** [comment]
I choose MIT license.
